/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class parsing_AST_Node */

#ifndef _Included_parsing_AST_Node
#define _Included_parsing_AST_Node
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
