/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class parsing_AST */

#ifndef _Included_parsing_AST
#define _Included_parsing_AST
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     parsing_AST
 * Method:    isPair
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_parsing_AST_isPair
  (JNIEnv *, jclass, jlong);

/*
 * Class:     parsing_AST
 * Method:    isAtom
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_parsing_AST_isAtom
  (JNIEnv *, jclass, jlong);

/*
 * Class:     parsing_AST
 * Method:    size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_parsing_AST_size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     parsing_AST
 * Method:    getAtom
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_parsing_AST_getAtom
  (JNIEnv *, jclass, jlong);

/*
 * Class:     parsing_AST
 * Method:    getCar
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_parsing_AST_getCar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     parsing_AST
 * Method:    getCdr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_parsing_AST_getCdr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     parsing_AST
 * Method:    getRow
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_parsing_AST_getRow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     parsing_AST
 * Method:    getCol
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_parsing_AST_getCol
  (JNIEnv *, jclass, jlong);

/*
 * Class:     parsing_AST
 * Method:    get
 * Signature: (Ljava/lang/String;)Lparsing/AST;
 */
JNIEXPORT jobject JNICALL Java_parsing_AST_get
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
