/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class parsing_TinyaJP */

#ifndef _Included_parsing_TinyaJP
#define _Included_parsing_TinyaJP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     parsing_TinyaJP
 * Method:    parseFile
 * Signature: (Ljava/lang/String;)Lparsing/AST;
 */
JNIEXPORT jobject JNICALL Java_parsing_TinyaJP_parseFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     parsing_TinyaJP
 * Method:    parseString
 * Signature: (Ljava/lang/String;)Lparsing/AST;
 */
JNIEXPORT jobject JNICALL Java_parsing_TinyaJP_parseString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     parsing_TinyaJP
 * Method:    lastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_parsing_TinyaJP_lastError
  (JNIEnv *, jobject);

/*
 * Class:     parsing_TinyaJP
 * Method:    lastErrorLine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_parsing_TinyaJP_lastErrorLine
  (JNIEnv *, jobject);

/*
 * Class:     parsing_TinyaJP
 * Method:    lastErrorColumn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_parsing_TinyaJP_lastErrorColumn
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
